# global.R
library(shiny)
library(cbsodataR)
library(bslib)
library(readr)
library(ggplot2)
# library(readxl)
library(dplyr)
library(tidyr)
library(tidytext)
# library(patchwork)
library(stringr)
# library(ggpattern)
#library(xlsx)
#library(openxlsx)
# library(reshape)
# library(viridisLite)
# library(scales)
library(stringr)
# library(gplots)
# library(kohonen)
# library(stringi)
# library(config)
